### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by samsonsin** [acidjazz/drmon#1]
Hello, i cannot get this program to work. The input fluxgate is not interacting with the program. Even if i manually change the value (via the monitor), the fluxgate's value stays the same. There are no error messages provided by the computer either so it is recognising it. I have tried placing the modem on multiple sides of the fluxgate too. Any ideas?

**Comment by acidjazz** [comment]
Can I get some pictures of your setup so i can get an idea? what happens when you run startup? does the screen connect and show up?

**Comment by acidjazz** [comment]
This was resolved
