### ISSUE TITLE
Field strenght always falling

### ISSUE THREAD

**Issue by Kirasaya** [acidjazz/drmon#11]
Well as the title says the programm doesnt keep the shield strengh at 50% it increases the input, but not enough to keep it up apperently. It works if I manually adjust the value with the monitor, so the programm should be correctly hoocked up and energy is also enough provided. Also it doesnt try to reach the output I set if i set it to 300k rf/t and it was at 210k rf/t the output goes down instead of going up to 300k.

**Comment by acidjazz** [comment]
@Kirasaya is the server you're on public at all?

**Comment by Kirasaya** [comment]
@acidjazz Its my own nitrado server, anyone with the IP and the responding mods (wich I all have in a dropbox file) could join on it, so i guess that counts as public?

**Comment by Kirasaya** [comment]
@acidjazz Went ahead and made 2 screenshots, first one a bit after starting the reactor:
http://imgur.com/IpE9tIx

Second one, 1 minute later same settings: http://imgur.com/fgsJHhA

Using the same setup as seen in this video: https://www.youtube.com/watch?v=8rBhQP1xqEU

**Comment by Kirasaya** [comment]
Found what was wrong finally, after setting up a second draconic energy core and everything going crazy. The tesseract on the recieving flux gate was on send and recieve that somehow messed all of that up, after putting it to send only it now works as intended. So yeah this can get closed, thanks for looking into it though.
