### ISSUE TITLE
Script Simply Does Not Work.

### ISSUE THREAD

**Issue by swartwoutme23** [acidjazz/drmon#18]
I am recent to Git Hub scripts so I might have botched something while putting in the code, but other than that, every individual line of code I enter, eventually, like, twelve of them in a row start spitting back errors.

**Comment by swartwoutme23** [comment]
Note: I am using the only version compatible for me which is 1.7.10

**Comment by spannerman79** [comment]
Did you read the very bottom on the README @swartwoutme23 ? https://github.com/acidjazz/drmon/issues/9#issuecomment-277910288

Even though its listed for Skyfactory pastebin changed its API from http to https.

**Comment by swartwoutme23** [comment]
No I did not see that. Thank you.
