### ISSUE TITLE
Reactor Output Incorrect

### ISSUE THREAD

**Issue by Daishar** [acidjazz/drmon#20]
Hello, I'm having an issue in single player. After setting up the program for the first time, everything works fine. When I restart the game my actual reactor output no longer matches what I've set on the monitor, being lower by 33%. With 1 million RF/t set on output, the output gate is only accepting 666 thousand RF/t. I can sometimes fix this temporarily by disconnecting the gates and monitor, restarting my single player game and reconnecting everything.

![2018-02-24_12 25 26](https://user-images.githubusercontent.com/36797862/36633244-ec04a570-195f-11e8-9120-f4ee7dfb4131.png)

![2018-02-24_12 25 37](https://user-images.githubusercontent.com/36797862/36633249-fd914b9a-195f-11e8-9c22-561ca8d7b777.png)

![2018-02-24_12 25 44](https://user-images.githubusercontent.com/36797862/36633251-03f473e0-1960-11e8-9f6c-da3162e35705.png)

![2018-02-24_12 25 47](https://user-images.githubusercontent.com/36797862/36633256-0cd4030e-1960-11e8-8954-f8ed30ae14ea.png)

(Edit)
After disconnecting all modems, picking up the advanced computer, restarting the game, replacing the computer and reinstalling the program, it works, until I restart the game again. Interesting to note is that not every restart of the game causes this bug, It seems to happen randomly after 1 to 4 times starting the game.

![2018-02-24_13 09 34](https://user-images.githubusercontent.com/36797862/36633490-b2d63f98-1964-11e8-8eea-1e74d5690dce.png)

(Edit 2)
After further testing this seems to not be a problem with the program at all, rather the flux gate itself. Applying a redstone signal resets the flux gate and forces it to function correctly.

**Comment by GhostShot3** [comment]
Texture ?
