### ISSUE TITLE
Auto Input gate doesnt work.

### ISSUE THREAD

**Issue by Meticrobotic** [acidjazz/drmon#23]
I tryed the program but the auto that change RF/t on the input gate doesnt want to change by it own and i do not know why. On Minecraft 1.12.2 . it just stays on 10,000rf/t know and doesnt change. i know it is warming up just becasue i restared it.

**Comment by spannerman79** [comment]
You did read the readme fully right? https://github.com/acidjazz/drmon/blob/master/README.md

**Comment by Meticrobotic** [comment]
Yes I have Every thing works but not auto

**Comment by spannerman79** [comment]
Well you didn't read the readme fully because it clearly states its for 1.7.10

**Comment by Meticrobotic** [comment]
I thought it could work with 1.12.2 too but ok. then i need to find another thing to control it

**Comment by spannerman79** [comment]
From the README.md

**You will need to edit references within the code for any version higher to reflect any changes made to Draconic Evolution past its 1.7.10 release.**

**Comment by Meticrobotic** [comment]
Then I need to look into the code to edit something so it works with my version.

**Comment by acidjazz** [comment]
@Meticrobotic a PR to support 1.12.x would be greatly appreciated!, thanks for the clarificaitons @spannerman79

**Comment by BartyB007** [comment]
> Then I need to look into the code to edit something so it works with my version.

well this is a extreme long shot 5 years later but did you ever fix this?
