### ISSUE TITLE
1.12.2 No valid fluxgate was found

### ISSUE THREAD

**Issue by TNTTheLagger** [acidjazz/drmon#30]
Help i installed mc 1.12.2 and have run in to a problem whit the reactor.

The the error is startup:51: No valid fluxgate was found

**Comment by spannerman79** [comment]
Did you read https://github.com/acidjazz/drmon#what-is-this ?

**Comment by TNTTheLagger** [comment]
I know i tried whit the forks for 1.12.2 but the same happens

**Comment by spannerman79** [comment]
Then why open an issue on this issue tracker when your complaing about another fork for which this issue tracker has no bearing on??
