### ISSUE TITLE
startup throws up an error

### ISSUE THREAD

**Issue by TakeyaSaito** [acidjazz/drmon#32]
so when i get to starting this thing i get an error
"startup:178: attempt to concatenate strong and boolean"

any idea why this might be happening? im playing on the ATM modpack

**Comment by spannerman79** [comment]
did you read https://github.com/acidjazz/drmon/blob/master/README.md#what-is-this fully?

**Comment by TakeyaSaito** [comment]
ahhh .... yeh i see the problem now, ignore me

**Comment by abrookes-1** [comment]
For the future I got this to work in 1.12 by adding tostring() in line 178 around the boolean variable being printed

**Comment by BartyB007** [comment]
> For the future I got this to work in 1.12 by adding tostring() in line 178 around the boolean variable being printed

probably a long shot but I am a total noob at code and don't understand your comment. I put line 17 in the parathesis?

**Comment by BartyB007** [comment]
> ahhh .... yeh i see the problem now, ignore me

hey this is a very long shot since it has been years but do you remember how you fixed it?

**Comment by TakeyaSaito** [comment]
> > ahhh .... yeh i see the problem now, ignore me
> 
> hey this is a very long shot since it has been years but do you remember how you fixed it?

Sorry, you are quite right, long time ago, can't for the life of me remember =/
