### ISSUE TITLE
App crashed after few min

### ISSUE THREAD

**Issue by GHOziLINA** [acidjazz/drmon#7]
fuelConversionRate: 846
temperature: 7378.53
fieldStrength: 5.0116072E7
fieldDrainRate: 116238
generationRate: 649335
status: online
energySaturation: 153503950
maxFuelConversion: 10368
fuelConversion: 444.188
maxFieldStrength: 100000000
maxEnergyStaturation: 1000000000
Output Gate: 650000
Input gate: 232476
Java Exception Thrown:
Java.lang.NullPointerException

and this error other times

Java Exception Thrown:
Java.lang.IndexOutOfBoundsException: Index:0, Size: 1

i keep getting that Java error after so 2-5 min of the app running

**Comment by piepie62** [comment]
Is the reactor always chunkloaded? Reloading it is what seems to make me get this error. It happened a few times before I realized that the entire thing wasn't loaded; maybe try chunkloading every single block of it?

**Comment by acidjazz** [comment]
@GHOziLINA can i get a full dump of your crash log?

**Comment by GHOziLINA** [comment]
seems to have been server side, problem server admin fixed running smooth as a baby's behind now, thanks
really nice program btw
